apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-serving-pv-claim
  namespace: model-serving
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
